------------------
--AR_FS Dormant accounts >=90 days
------------------

ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS';

With FIRSTTRANSACTION as
(select distinct MERCHANT_CUSTOMER_ID
	, SIGNUP_DAY
	, FIRST_TRANSACTION_DAY as First_txn_day
from CODENAME_DDL.D_ACCOUNT 
where FPS_ACCOUNT_IDTY_STATE in ('IDTY_PASSED')
order by FIRST_TXN_DAY desc), 

SECONDTRANSACTION as
(select DISTINCT MERCHANT_CUSTOMER_ID
	, CODENAME_TRANSACTION_ID, PREV_TXN
	, TRANSACTION_DAY, PREV_TXN_DAY
	, (TRANSACTION_DAY-PREV_TXN_DAY) AS PREV_TXN_DELTA
from 
	(select distinct CODENAME_TRANSACTION_ID, TRANSACTION_DAY, MERCHANT_CUSTOMER_ID, 
	LAG(CODENAME_TRANSACTION_ID,1,'NULL') over(partition by MERCHANT_CUSTOMER_ID order by TRANSACTION_DAY) as PREV_TXN,
	LAG(TRANSACTION_DAY, 1, null) over(partition by MERCHANT_CUSTOMER_ID order by TRANSACTION_DAY) as PREV_TXN_DAY
	from CODENAME_DDL.D_CODENAME_SALE_TRANSACTIONS
	where Transaction_type not in 'CASH'))

select distinct a.MERCHANT_CUSTOMER_ID
, '20' as MARKETPLACE_ID
, B.FIRST_TXN_DAY
, a.PREV_TXN_DAY
, B.SIGNUP_DAY
, (B.FIRST_TXN_DAY - B.SIGNUP_DAY) as DELTA_FROM_SIGNUP
, a.PREV_TXN_DELTA
from SECONDTRANSACTION a
, FIRSTTRANSACTION B
where a.MERCHANT_CUSTOMER_ID = B.MERCHANT_CUSTOMER_ID 

and (((B.FIRST_TXN_DAY - B.SIGNUP_DAY) >=30
and B.FIRST_TXN_DAY>=sysdate - 1.1) 
or
((a.TRANSACTION_DAY-a.PREV_TXN_DAY) >=90 
and a.TRANSACTION_DAY>=sysdate - 1.1))

order by DELTA_FROM_SIGNUP, PREV_TXN_DELTA
desc